name: Create PR
on:
  workflow_dispatch:
  schedule:
    - cron:  '10,20,30,40,50 * * * *'
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Changes
        run: |
          echo "foo" >> README.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{secrets.PAT}}
          branch-suffix: random
          delete-branch: true
